# Generated by Django 2.2.14 on 2020-08-31 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_img_home', models.FileField(blank=True, null=True, upload_to='documents/img/')),
                ('file_img_2', models.FileField(blank=True, null=True, upload_to='documents/img/')),
                ('file_img_3', models.FileField(blank=True, null=True, upload_to='documents/img/')),
                ('title', models.CharField(max_length=100)),
                ('subTitle', models.CharField(default='', max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('value', models.IntegerField()),
                ('material', models.CharField(default='', max_length=100)),
                ('color', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(default='', max_length=100)),
                ('sizes_list', models.TextField(default='[S,M,L]', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('type_product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostIcenParty.TypeProduct')),
                ('type_store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostIcenParty.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='BuyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_contact', models.CharField(max_length=100)),
                ('name_contact', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('type_house', models.CharField(max_length=100)),
                ('units', models.IntegerField(default=1)),
                ('value', models.CharField(default='0', max_length=100)),
                ('product_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostIcenParty.Product')),
                ('status_buy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostIcenParty.StatusBuy')),
            ],
        ),
    ]
