# Generated by Django 2.2.14 on 2020-08-31 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostIcenParty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyproduct',
            old_name='number_contact',
            new_name='phone_contact',
        ),
    ]
