# Generated by Django 2.2.14 on 2020-09-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostIcenParty', '0002_auto_20200831_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='size',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
