# Generated by Django 2.2.14 on 2020-09-03 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostIcenParty', '0006_auto_20200903_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyproduct',
            options={'ordering': ['units']},
        ),
        migrations.AlterUniqueTogether(
            name='buyproduct',
            unique_together={('status_buy', 'units')},
        ),
    ]
