# Generated by Django 2.2.14 on 2020-09-03 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostIcenParty', '0007_auto_20200903_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyproduct',
            options={},
        ),
        migrations.AlterField(
            model_name='buyproduct',
            name='status_buy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostIcenParty.StatusBuy'),
        ),
        migrations.AlterUniqueTogether(
            name='buyproduct',
            unique_together=set(),
        ),
    ]
