# Generated by Django 2.2.14 on 2020-09-03 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostIcenParty', '0009_auto_20200903_0142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statusbuy',
            unique_together={('name',)},
        ),
    ]
