# Generated by Django 2.2.14 on 2020-09-03 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostIcenParty', '0005_auto_20200902_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='status_buy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='hostIcenParty.StatusBuy'),
        ),
    ]
