# Generated by Django 2.2.14 on 2020-09-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostIcenParty', '0014_auto_20200910_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproduct',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
