# Generated by Django 2.2.14 on 2020-09-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostIcenParty', '0017_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
