# Generated by Django 2.2.14 on 2020-09-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostIcenParty', '0018_delete_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyProduct',
            new_name='OrdersProduct',
        ),
    ]
